// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.pizzashop;

import com.springsource.roo.pizzashop.Authorities;
import com.springsource.roo.pizzashop.AuthoritiesDataOnDemand;
import com.springsource.roo.pizzashop.AuthoritiesIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AuthoritiesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AuthoritiesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AuthoritiesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AuthoritiesIntegrationTest: @Transactional;
    
    @Autowired
    private AuthoritiesDataOnDemand AuthoritiesIntegrationTest.dod;
    
    @Test
    public void AuthoritiesIntegrationTest.testCountAuthoritieses() {
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", dod.getRandomAuthorities());
        long count = Authorities.countAuthoritieses();
        Assert.assertTrue("Counter for 'Authorities' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AuthoritiesIntegrationTest.testFindAuthorities() {
        Authorities obj = dod.getRandomAuthorities();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to provide an identifier", id);
        obj = Authorities.findAuthorities(id);
        Assert.assertNotNull("Find method for 'Authorities' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Authorities' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AuthoritiesIntegrationTest.testFindAllAuthoritieses() {
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", dod.getRandomAuthorities());
        long count = Authorities.countAuthoritieses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Authorities', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Authorities> result = Authorities.findAllAuthoritieses();
        Assert.assertNotNull("Find all method for 'Authorities' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Authorities' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AuthoritiesIntegrationTest.testFindAuthoritiesEntries() {
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", dod.getRandomAuthorities());
        long count = Authorities.countAuthoritieses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Authorities> result = Authorities.findAuthoritiesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Authorities' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Authorities' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AuthoritiesIntegrationTest.testFlush() {
        Authorities obj = dod.getRandomAuthorities();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to provide an identifier", id);
        obj = Authorities.findAuthorities(id);
        Assert.assertNotNull("Find method for 'Authorities' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAuthorities(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Authorities' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthoritiesIntegrationTest.testMergeUpdate() {
        Authorities obj = dod.getRandomAuthorities();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to provide an identifier", id);
        obj = Authorities.findAuthorities(id);
        boolean modified =  dod.modifyAuthorities(obj);
        Integer currentVersion = obj.getVersion();
        Authorities merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Authorities' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthoritiesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", dod.getRandomAuthorities());
        Authorities obj = dod.getNewTransientAuthorities(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Authorities' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Authorities' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Authorities' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AuthoritiesIntegrationTest.testRemove() {
        Authorities obj = dod.getRandomAuthorities();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Authorities' failed to provide an identifier", id);
        obj = Authorities.findAuthorities(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Authorities' with identifier '" + id + "'", Authorities.findAuthorities(id));
    }
    
}
